// React-WeatherApp/src/components/InfoPanel/InfoPanel.jsx
import React from "react";
import { useDispatch, useSelector } from "react-redux";
import { useTranslation } from "react-i18next";

import { convertTemp } from "store/reducer/waetherReducer";

import "./InfoPanel.scss";

const InfoPanel = () => {
	const dispatch = useDispatch();

	const weather = useSelector((state) => state.weather);

	const { t } = useTranslation();

	const onClickHandler = () => {
		dispatch(convertTemp(weather.weatherInfo.temp));
	};

	return (
		<div className="card">
			<div>
				<span>{t("current_temp")}</span>

				{weather?.weatherInfo?.temp?.current && (
					<button className="temp" onClick={() => onClickHandler()}>
						{weather?.weatherInfo?.temp?.current} &deg;{weather.unit}
					</button>
				)}
			</div>

			<div className="minMaxTemp">
				<div>
					<span>{t("min_temp")}</span>

					{weather?.weatherInfo?.temp?.minTemp && (
						<button className="temp" onClick={() => onClickHandler()}>
							{weather?.weatherInfo?.temp?.minTemp} &deg;{weather.unit}
						</button>
					)}
				</div>

				<span className="right-border" />

				<div>
					<span>{t("max_temp")}</span>

					{weather?.weatherInfo?.temp?.maxTemp && (
						<button className="temp" onClick={() => onClickHandler()}>
							{weather?.weatherInfo?.temp?.maxTemp} &deg;{weather.unit}
						</button>
					)}
				</div>
			</div>

			<div>
				<span>{weather?.weatherInfo?.condition?.text}</span>
				<img
					src={weather?.weatherInfo?.condition?.icon}
					alt={weather?.weatherInfo?.condition?.text}
				/>
			</div>
		</div>
	);
};

export default InfoPanel;

// Vue-WeatherApp/src/components/InfoPanel.vue
<template>
  <div class="card">
    <div class="currentTemp">
      <span>{{ $t('current_temp') }}</span>
      <button
        v-if="weatherInfo?.temp?.current"
        class="temp"
        @click="onClickHandler(weatherInfo.temp)"
      >
        {{ weatherInfo.temp.current }} &deg;{{ unit }}
      </button>
    </div>

    <div class="minMaxTemp">
      <div>
        <span>{{ $t('min_temp') }}</span>
        <button
          v-if="weatherInfo?.temp?.minTemp"
          class="temp"
          @click="onClickHandler(weatherInfo.temp)"
        >
          {{ weatherInfo.temp.minTemp }} &deg;{{ unit }}
        </button>
      </div>

      <div>
        <span>{{ $t('max_temp') }}</span>
        <button
          v-if="weatherInfo?.temp?.maxTemp"
          class="temp"
          @click="onClickHandler(weatherInfo.temp)"
        >
          {{ weatherInfo.temp.maxTemp }} &deg;{{ unit }}
        </button>
      </div>
    </div>

    <div v-if="weatherInfo?.condition">
      <span>{{ weatherInfo?.condition?.text }}</span>
      <img :src="weatherInfo?.condition?.icon" :alt="weatherInfo?.condition?.text" />
    </div>
  </div>
</template>

<script>
import { storeToRefs } from 'pinia'

import { useWeatherStore } from '@/stores/weatherStore'

export default {
  name: 'InfoPanel',
  setup() {
    const weatherStore = useWeatherStore()
    const { weatherInfo, unit } = storeToRefs(weatherStore)

    const onClickHandler = (temps) => {
      weatherStore.convertTemp(temps)
    }

    return { weatherInfo, unit, onClickHandler }
  },
}
</script>

<style lang="scss" scooped>
@import url('./scss/InforPanel.scss');
</style>
